services:
  order_service:
    build:
      context: ./backend/order_service
      dockerfile: Dockerfile
    container_name: order_service
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - ./backend/order_service:/app
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:17
    container_name: food_order_db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 127.0.0.1 -p 5432" ]
      interval: 5s
      retries: 10
      timeout: 5s

volumes:
  postgres_db: