version: "3.8"

services:
  order_service:
    build:
      context: ./backend/order_service
      dockerfile: Dockerfile
    container_name: order_service
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - ./backend/order_service:/app
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      - PYTHONPATH=/app
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"

  order_consumer:
    build:
      context: ./backend/order_service
      dockerfile: Dockerfile
    container_name: order_consumer
    env_file:
      - .env
    volumes:
      - ./backend/order_service:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      - PYTHONPATH=/app
    command: sh -c "python order_consumer/consumer.py"

  payment_service:
    build:
      context: ./backend/payment_service
      dockerfile: Dockerfile
    container_name: payment_service
    ports:
      - "8002:8000"
    env_file:
      - .env
    volumes:
      - ./backend/payment_service:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - PYTHONPATH=/app
    command: sh -c "sleep 10 && python app.py"

  db:
    image: postgres:17
    container_name: food_order_db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 127.0.0.1 -p 5432" ]
      interval: 5s
      retries: 10
      timeout: 5s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmqctl status" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_db:
